use_frameworks!

platform :ios, '10.0'

target 'iOSAIChatBotSDK_Example' do
  pod 'iOSAIChatBotSDK', :path => '../'

  target 'iOSAIChatBotSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
